name: Build BETweaker

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  Platform: X64
  ChakraCore_version: cc_windows_all_1_11_24

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
     
    - name: Pull submodule
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: FetchSDK.cmd
      shell: cmd
     
    - name: Download Server
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/BDS
        ServerLink=$(cat 'LINK.txt')
        curl -L -o D:/BDS/server.zip "$ServerLink"
        unzip D:/BDS/server.zip -d D:/BDS > /dev/null
      shell: bash

    - name: Build Library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd SDK/Tools
        mkdir ../LiteLoader
        mkdir ../LiteLoader/Lib
        ./LibraryBuilder.exe D:/BDS
        mv ../LiteLoader/Lib/* ../Lib/
      shell: bash

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        MSBuild.exe ./BETweaker.sln -property:Configuration=Release
      shell: bash
    
    - name: MkDirs
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir D:/out/sdk
        mkdir D:/out/sdk/Lib
        mkdir D:/out/sdk/Header
        mkdir D:/out/plugins
    
    - name: Copy Out Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cp x64/Release/*.dll D:/out/plugins
        cp x64/Release/*.lib D:/out/sdk/Lib
        cp x64/Release/*.pdb D:/out/plugins
        cp -r plugins/* D:/out/plugins
      shell: bash

    - name: Upload plugins
      uses: actions/upload-artifact@v1.0.0
      with:
        name: plugins
        path: D:/out/plugins


    - name: Compress to zip
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        7z a D:/out/plugins.zip D:/out/plugins
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workspace }}\CHANGELOG.txt
        files: |
          D:/out/plugins.zip
          D:/out/SDK.zip
      env:
          GITHUB_REPOSITORY: dreamguxiang/BETweaker
